server:
  port: 50001
spring:
  datasource:
    url: jdbc:mysql://115.159.213.143:3307/dubbo-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980706
  redis:
    port: 6379
    host: 115.159.213.143
    database: 3
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**.xml
  type-aliases-package: com.qc.yx.bean

dubbo:
  application:
    name: demo-lesson-service
  registry:
    address: zookeeper://115.159.213.143:2181
  scan:
    base-packages: com.qc.yx.service.impl
  protocol:
    port: -1
  consumer:
    check: false