server:
  port: 50002
spring:
  datasource:
    url: jdbc:mysql://115.159.213.143:3307/dubbo-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980706
  application:
    name: demo-student-service
  redis:
    database: 5
    host: 115.159.213.143
    port: 6379
mybatis:
  configuration:
    map-underscore -to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: com.qc.yx.bean
dubbo:
  registry:
    address: zookeeper://115.159.213.143:2181
  application:
    name: demo-lesson-student-service
  scan:
    base-packages: com.qc.yx.service.impl
  protocol:
    port: -1
  consumer:
    check: false